version: '2'

services:
    nginx:
        image: nginx:1.13.6
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php

    php:
        build: ./docker/php/
        volumes:
            - .:/var/www/html
        links:
            - database

    database:
        image: mysql:5.7
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
        volumes:
            - ./backup/data/mysql:/var/lib/mysql
        ports:
            - "33067:3306"